# Generated by Django 2.2 on 2021-06-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosplayapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='user',
            new_name='username',
        ),
    ]
