# Generated by Django 2.2 on 2021-06-09 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosplayapp', '0003_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_likes',
            field=models.ManyToManyField(related_name='comment_likes', to='cosplayapp.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_likes',
            field=models.ManyToManyField(related_name='message_likes', to='cosplayapp.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
