# Generated by Django 2.2 on 2021-06-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosplayapp', '0004_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=45)),
                ('age', models.IntegerField(max_length=2)),
                ('fav_character', models.CharField(max_length=45)),
                ('about_me', models.TextField()),
                ('profileUpdated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to='cosplayapp.User')),
            ],
        ),
    ]
