# Generated by Django 2.2 on 2021-06-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosplayapp', '0005_auto_20210608_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_character',
            field=models.CharField(default='fav_character', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='location', max_length=45),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
