# Generated by Django 2.2 on 2021-06-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosplayapp', '0006_auto_20210608_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('fav_character', models.CharField(max_length=45)),
                ('about_me', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fav_character',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
