# Generated by Django 2.2 on 2021-06-10 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosplayapp', '0013_auto_20210610_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cosplayapp.User'),
        ),
    ]
