# Generated by Django 2.2 on 2021-06-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosplayapp', '0017_remove_comment_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_likes',
            new_name='user_likes',
        ),
    ]
